### PR TITLE
Add Kotlin/Native(iOS) project

### PR DESCRIPTION
**Pull request by kikuchy**
## Issue
- https://github.com/DroidKaigi/conference-app-2018/issues/66

## Overview (Required)
- Create iOS app project in `ios/`
- Define CMake project
    - You can open `ios/` with CLion and edit Kotlin sources.
- Define Xcode project
    - You can build the app from Run button.
- Not working
    - But we can start writing code. Put .kt files into `ios/src/main/kotlin/`.

## Links
- https://qiita.com/noripi/items/4ee969c48b3da5ca6fbd
- https://qiita.com/oboenikui/items/07481c6f44fe3e2c4440

### CODE REVIEW

**Comment by punchdrunker** [comment]
👀

**Comment by punchdrunker** [comment]
Did you build in Xcode? I got some errors below

```
Download https://jcenter.bintray.com/com/github/bumptech/glide/annotations/4.4.0/annotations-4.4.0.jar
Download https://jcenter.bintray.com/com/google/errorprone/javac-shaded/9-dev-r4023-3/javac-shaded-9-dev-r4023-3.jar
Download https://jcenter.bintray.com/com/google/dagger/dagger-android-processor/2.13/dagger-android-processor-2.13.jar
:ios:checkKonanCompiler
:ios:compileKonanAppIphone
KtFile: main.kt
Undefined symbols for architecture arm64:
  "_EntryPointSelector", referenced from:
      _Konan_start in combined2603687241364282890.o
ld: symbol(s) not found for architecture arm64
error: could not find 'main' in '<root>' package.
error: linker invocation reported errors
:ios:compileKonanAppIphone FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':ios:compileKonanAppIphone'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 27s
2 actionable tasks: 2 executed
```

**Comment by punchdrunker** [comment]
ah, I got it. This PR is a just only initial commit, right?

**Comment by kikuchy** [comment]
> This PR is a just only initial commit

Yes!!
But it's not kind to contributers, now I add main function and minimum classes.

And add .kt files and other setting files references to xcodeproj to clear `src/` file trees.

**Comment by punchdrunker** [comment]
GJ 💯

**Comment by kikuchy** [comment]
Thank you very much!!

**Pull request merged**
